### PR TITLE
feat: esbuild benchmark

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
example: 
image

Only run `rspack` and `esbuild` in order to save time.

### CODE REVIEW

**Comment by strager** [comment]
I am on macOS AArch64 (M1 chip):
```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.2
BuildVersion:		22D49
```

**Comment by hardfist** [comment]
> I tried your PR at commit [1f8b192](https://github.com/web-infra-dev/performance-compare/commit/1f8b1927ee01412727303e543330a3bf0c9d0540) but it didn't work for me:
> 
> ```
> $ node benchmark.mjs
> Running cold run 3 times
> 
> Running: Rspack (1)
> Running: Rspack (2)
> Running: Rspack (3)
> Running: esbuild (1)
> node:internal/process/esm_loader:42
>       internalBinding('errors').triggerUncaughtException(
>                                 ^
> 
> page.waitForEvent: Timeout 30000ms exceeded while waiting for event "console"
> =========================== logs ===========================
> waiting for event "console"
> ============================================================
>     at file:///Users/strager/tmp/Projects/rspack-performance-compare/benchmark.mjs:68:37 {
>   name: 'TimeoutError'
> }
> 
> Node.js v20.2.0
> 
> $ pnpm --version
> 8.5.1
> $ node --version
> v20.2.0
> ```

it seems live-reload broken on your computer, maybe you can checkout the devtool panel of browser when esbuild runs

**Comment by strager** [comment]
> it seems live-reload broken on your computer, maybe you can checkout the devtool panel of browser when esbuild runs

I don't know what you mean by 'browser'. I'm running with Node.js. I don't see any browser windows created by the tool. How can I open the browser dev tools?

> Can you try again?

I got the same timeout error at commit 25a361e2cbc49a34866fff2f51f39bc73c99c133.

**Comment by hardfist** [comment]
@strager can pull again, and if you still have problems please try run `pnpm start:esbuild` and see the browser result, and change some code in src to see if HMR works?

**Comment by strager** [comment]
> please try run `pnpm start:esbuild`

This helped me diagnose the problem. It told me this:
```
$ pnpm start:esbuild

> performance-compare@0.0.0 start:esbuild /Users/strager/tmp/Projects/rspack-performance-compare
> node ./benchmark/esbuild.mjs --watch

/Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1156
              return reject(new Error(error2));
                            ^

Error: listen tcp 127.0.0.1:1235: bind: address already in use
    at /Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1156:29
    at responseCallbacks.<computed> (/Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:750:9)
    at Socket.readFromStdout (/Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:305:9)
    at Readable.push (node:internal/streams/readable:242:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.2.0
 ELIFECYCLE  Command failed with exit code 1.
```
I killed the process running on that port (`/Users/strager/tmp/Projects/rspack-performance-compare/node_modules/.pnpm/@esbuild+darwin-arm64@0.17.19/node_modules/@esbuild/darwin-arm64/bin/esbuild --service=0.17.19 --ping`), then tried again:
```
$ pnpm start:esbuild

> performance-compare@0.0.0 start:esbuild /Users/strager/tmp/Projects/rspack-performance-compare
> node ./benchmark/esbuild.mjs --watch

node:events:489
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::12345
    at Server.setupListenHandle [as _listen2] (node:net:1823:16)
    at listenInCluster (node:net:1871:12)
    at Server.listen (node:net:1959:7)
    at file:///Users/strager/tmp/Projects/rspack-performance-compare/benchmark/esbuild.mjs:42:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1850:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 12345
}

Node.js v20.2.0
 ELIFECYCLE  Command failed with exit code 1.
```
I killed the process running on *that*, then `pnpm start:esbuild` and `node benchmark.mjs` worked.

Here are my results (n=1; not a clean run):
```
┌─────────┬───────────────────┬─────────────────────────────────────────────────────────┬───────────────┬───────────────┬─────────────────┐
│ (index) │       name        │                      startup time                       │ Root HMR time │ Leaf HMR time │ production time │
├─────────┼───────────────────┼─────────────────────────────────────────────────────────┼───────────────┼───────────────┼─────────────────┤
│    0    │     'Rspack'      │  '833.33ms (including server start up time: 146.67ms)'  │  '298.67ms'   │  '302.67ms'   │   '733.33ms'    │
│    1    │     'esbuild'     │  '396.67ms (including server start up time: 53.33ms)'   │  '749.00ms'   │  '1394.00ms'  │   '201.33ms'    │
│    2    │    'Turbopack'    │  '2564.67ms (including server start up time: 12.83ms)'  │   '22.33ms'   │   '24.33ms'   │       ''        │
│    3    │ 'Webpack (babel)' │ '5195.00ms (including server start up time: 4126.33ms)' │  '202.67ms'   │  '164.33ms'   │   '7758.67ms'   │
│    4    │  'Webpack (swc)'  │ '2575.00ms (including server start up time: 1523.33ms)' │  '197.67ms'   │  '187.67ms'   │   '4374.33ms'   │
│    5    │      'Vite'       │ '2944.33ms (including server start up time: 230.00ms)'  │  '104.33ms'   │  '124.67ms'   │   '1791.00ms'   │
│    6    │   'Vite (swc)'    │ '1481.33ms (including server start up time: 125.67ms)'  │  '134.00ms'   │  '122.00ms'   │   '1675.33ms'   │
│    7    │      'Farm'       │  '831.33ms (including server start up time: 218.67ms)'  │  '132.67ms'   │   '74.33ms'   │       ''        │
│    8    │     'Parcel'      │                       '2110.33ms'                       │   '90.00ms'   │  '104.67ms'   │   '4052.00ms'   │
└─────────┴───────────────────┴─────────────────────────────────────────────────────────┴───────────────┴───────────────┴─────────────────┘
```

**Review by hardfist — APPROVED** [review]

**Comment by hardfist** [comment]
glad it works, @strager if you need more benchmark data please let me know

**Pull request merged**
